"use strict";
const priceError = 'Invalid price for this product!';
const emptyError = 'This field must be filled!';
const colorError = 'Invalid color for this item!';
const lengthError = 'Length entered is out of boundary!';
const sizeError = 'Size entered is not allowed!';
const fabricError = 'No such fabric for this item!';
const pocketError = 'Invalid number of pockets!';
const perimiterError = 'Invalid perimiter entered!';
const thicknessError = 'Invalid thickness value!';
const heightError = 'Height entered is invalid!';
let generator = new Generator();
